### ISSUE TITLE
How to render form to edit primary key in New Page?

### ISSUE THREAD

**Issue by linhhdinh** [qor/admin#136]
How do I setup `QOR admin` to be able to edit the `catalog.ID` field  in New Page?

```
type Catalog struct {
	ID           string `gorm:"primary_key"`
	Host         string
}
```

**Comment by ole-optiopay** [comment]
What do you want to do?
Editing IDs is highly dangerous and can easily break the consistency of the DB.
Even admin users shouldn't be able to do it in my humble opinion.

**Comment by preslavrachev** [comment]
There is a trick you can try:

```go
myResource.EditAttrs("ID", "FirstName", "LastName")
myResource.NewAttrs("ID", "FirstName", "LastName")
myReource.Meta(&admin.Meta{Name: "ID", Type: "text"})
```

`myReource.Meta(&admin.Meta{Name: "ID", Type: "text"})` will make the ID among the editable fields
