### ISSUE TITLE
how to embeding custom html code in meta?

### ISSUE THREAD

**Issue by kaixinbuyu** [qor/admin#155]
can I using customized html returned to meta?
eg.

product.Meta(&admin.Meta{Name: "line-chart", Valuer: func(record interface{}, context *qor.Context) interface{} {
....
  return **"a d3.js line chart html and javascript code to be rendered in view "**
}})

**Comment by cryptix** [comment]
You do this by supplying a custom html template. The Valuer is only responsible for pre-processing the data that is handed to the template execution.

**Comment by kaixinbuyu** [comment]
thank you!
