### ISSUE TITLE
How to custom select many from other source(redis,.. without db)

### ISSUE THREAD

**Issue by luannt2909** [qor/admin#160]
Hi all, i want to add a resource to menu and its data is loaded from other source(redis).
So i custom func FindManyHandler
```
rediskey := Admin.AddResource(&keyvalue.KeyValue{}, &admin.Config{Menu: []string{"Key-Value Management"}, Name: "Redis Data"})
	rediskey.IndexAttrs("Key", "Value")
	rediskey.FindManyHandler = func(result interface{}, context *qor.Context) error {
		var redisData []*keyvalue.KeyValue
		//TODO: handle redisData
		db := context.GetDB()
		if _, ok := db.Get("qor:getting_total_count"); ok {
			total_count := len(redisData)
			result = &total_count
			return nil
		}
		result = &redisData
		return nil
	}
```
=> **No redis data to show.**
Maybe, it properly work only with dabatase
Are there anyway that i could custom it?
Thank for help

**Comment by cryptix** [comment]
If done this, not for redis though. I can’t remember the trick to return through the first parameter right now (on mobile) but can look it up later.

**Comment by luannt2909** [comment]
Thank for your response,
this is same as issue #113, i see.
So, could you tell me how to` decode records to results` that recommend on docs. I really confused about it.
```
res.FindManyHandler = func(results interface{}, context *qor.Context) error {
  // find records and decode them to results
}
```

**Comment by luannt2909** [comment]
Thank god, you are here
Your code resolved my issue ^-^.
thank you so much ^^
