### ISSUE TITLE
怎么实现点击一个字段的时候弹出show像图上的效果, 新版本已经不行了

### ISSUE THREAD

**Issue by zeropool** [qor/admin#167]
![image](https://user-images.githubusercontent.com/20485191/50472197-c5fdf000-09f2-11e9-8c82-e2f4b9b37dc3.png)

**Comment by jasonweng** [comment]
没明白你的意思

**Comment by zeropool** [comment]
@jasonweng 不好意思，发issue的时候手滑打错了，就是想实现，显示一个表里的所有数据的时候
比如UserID这个字段，显示成图上带链接的形式，点击他的时候，可以直接右边滑出关联的这条用户的信息

另外就是之前支持
```
web_member?filters[ID].Value=123
```
这样的，直接以ID为过滤器的试，现在不支持了

**Comment by zeropool** [comment]
@jasonweng 作者在吗, 不好意思打扰了，请帮忙看一下, 感谢qor这么好的项目~~
