### ISSUE TITLE
Proposal: many2many limit/search

### ISSUE THREAD

**Issue by slava-vishnyakov** [qor/admin#2]
First of all - wow! Thanks for awesome library. 

Let's say we have a simple table:

```
type User struct {
    gorm.Model
    Name     string
    Products []Product `gorm:"many2many:user_product"`
}

type Product struct {
    gorm.Model
    Name        string
    Description string
}
```

But, if I have 100 000 of products - the editor slows down to a halt, because I renders a dropdown with 100 000 elements. When I try to type a button - Chrome just hangs..

![image](https://cloud.githubusercontent.com/assets/817931/13748846/a9fe632c-ea0f-11e5-8e15-0b4040960302.png)

It would've been super-cool if there was an option to make something like LIMIT 1000 on request and have server-side LIKE '%..%' filtering.

Maybe something like:

```
    Products []Product `gorm:"many2many:user_product" qor:"limit:1000"`
```

Otherwise, bravo! It's a super-cool thing!

**Comment by jinzhu** [comment]
Thank you for your suggestion, we will look into this, and think to change this to ajax loading suggestions, which will has a better experience

**Comment by derlaft** [comment]
Made a dirty plugin to load this data over AJAX: https://github.com/trendever/ajaxor

**Comment by jinzhu** [comment]
added this feature for a while, closing this issue.
