### ISSUE TITLE
Is there any way to linkify a field containing URL?

### ISSUE THREAD

**Issue by ashishb** [qor/admin#224]
Is there any way to linkify a field containing URL? I didn't see any particular meta type which can do that. Do I have to build a custom template for that?

**Comment by raven-chen** [comment]
@ashishb hi, do you mean to display a field contains an URL as a clickable URL in the admin interface?

**Comment by ashishb** [comment]
Yes

**Comment by raven-chen** [comment]
You can do it by:

```go
        res.ShowAttrs("ID", "Name", "Link")
	res.Meta(&admin.Meta{
		Name: "Link",
		Valuer: func(value interface{}, ctx *qor.Context) interface{} {
			p := value.(*Product)
			return template.HTML(fmt.Sprintf("<a href=%q>%s</a>", p.Link, p.Link))
		},
	})
```

**Comment by ashishb** [comment]
Thanks a lot, this solves the problem by adding a new virtual field "Link". What if I already have a field "Link", which I want to display differently without changing the underlying value?

**Comment by raven-chen** [comment]
@ashishb  the `Link` here is not a virtual value, I didn't put other parts in the sample.
You can do whatever you want in the `Valuer` function. Adding prefix, suffix etc.

**Comment by ashishb** [comment]
@raven-chen Thanks. Sorry, I was probably not clear enough in my last question. The valuer is pretty powerful and can definitely do whatever I want. The issue with the code snippet you suggested is that it is adding a new virtual column `Link` even when I have an existing real column Link. It is not replacing the existing column. Let's say the name of the SQL column is `image_link`. 

I tried

```
res.Meta(&admin.Meta{
		Name: "Image Link",
		Valuer: func(value interface{}, ctx *qor.Context) interface{} {
			p := value.(*Product)
			return template.HTML(fmt.Sprintf("<a href=%q>%s</a>", p.Link, p.Link))
		},
	})
```

as well as 

```
res.Meta(&admin.Meta{
		Name: "image_link",
		Valuer: func(value interface{}, ctx *qor.Context) interface{} {
			p := value.(*Product)
			return template.HTML(fmt.Sprintf("<a href=%q>%s</a>", p.Link, p.Link))
		},
	})
```

In both the cases, a new virtual column gets added and the existing column titled `Image Link` remains as-is.

**Comment by ashishb** [comment]
So, the right way to this was to use `ImageLink` (or whatever the field name is defined in the ORM definition). Leaving here for future reference.
