### ISSUE TITLE
Multi-line "text" editing without resorting to rich_editor?

### ISSUE THREAD

**Issue by ashishb** [qor/admin#232]
Is there a way to get multi-line editing like `rich_editor` while still only having plain-text editing?

**Comment by raven-chen** [comment]
@ashishb  https://doc.getqor.com/admin/metas/text-input.html   `type: "text"` can do it.

**Comment by ashishb** [comment]
How? I wasn't able to find a way to make it a multi-line editor?

Ashish

**Comment by raven-chen** [comment]
`res.Meta(&admin.Meta{Name: "Description", Type: "text"})` like this

**Comment by ashishb** [comment]
Thanks. That's what I did but this creates a single line field. I am
looking to create a multi-line text field

**Comment by raven-chen** [comment]
@ashishb  if you are using mac. you should see an icon in the corner. drag it and you will get a multi-line text field.

![image](https://user-images.githubusercontent.com/230620/90005547-f4186c80-dcc9-11ea-8215-ef8af4d98d4d.png)

after

![image](https://user-images.githubusercontent.com/230620/90005656-1ad6a300-dcca-11ea-8ad5-f215d1e6dbab.png)

**Comment by ashishb** [comment]
Thanks. Sorry, I forgot to mention my OS (it is indeed Mac).
I was wondering if there is a more direct way of specifying number of
lines, say, I want the textfield (rather textarea) to be at least 10 lines.
Also, textarea allows anyone to press add a new line with enter/return
key.  A textfield does not.

Ashish

**Comment by raven-chen** [comment]
@ashishb 
It is a textarea with 1 row by default. QOR doesn't support specifying the row atm.

![image](https://user-images.githubusercontent.com/230620/90090105-beb96080-dd55-11ea-9923-a095e620546c.png)
