### ISSUE TITLE
Error when go get

### ISSUE THREAD

**Issue by mmanjoura** [qor/admin#32]
I am getting the following error trying the go git the example:
 github.com/qor/qor-example/config/auth
gocode/src/github.com/qor/qor-example/config/auth/auth.go:35: Auth.LayoutPath undefined (type *authboss.Authboss has no field or method LayoutPath)
gocode/src/github.com/qor/qor-example/config/auth/auth.go:36: Auth.LayoutFuncMaker undefined (type *authboss.Authboss has no field or method LayoutFuncMaker)

**Comment by Jeweller-Tsai** [comment]
@mmanjoura are you trying to play with the [QOR example](https://github.com/qor/qor-example), what's your go version? It requires 1.6 +

**Comment by chikyukotei** [comment]
I think that happens due to the authboss version (see `/vendor/` directory).
`qor/qor-example` uses old version.
Old version has LayoutPath field, but latest version has no field LayoutPath.
