### ISSUE TITLE
panic when access /admin url

### ISSUE THREAD

**Issue by listeng** [qor/admin#33]
Listening on: 9000
2016/08/05 17:27:41 Finish [GET] /admin Took 0.00ms
2016/08/05 17:27:41 http: panic serving [::1]:61764: runtime error: invalid memory address or nil pointer dereference
goroutine 22 [running]:
net/http.(_conn).serve.func1(0x115da100)
        E:/bin/go1.6/src/net/http/server.go:1389 +0xa2
panic(0x8319c0, 0x1148e030)
        E:/bin/go1.6/src/runtime/panic.go:443 +0x3fd
html/template.(_Template).escape(0x0, 0x0, 0x0)
        E:/bin/go1.6/src/html/template/template.go:79 +0x37
html/template.(_Template).Execute(0x0, 0x3208fb88, 0x114fe280, 0x883da0, 0x115da200, 0x0, 0x0)
        E:/bin/go1.6/src/html/template/template.go:101 +0x2b
github.com/qor/admin.(_Context).Execute(0x115da200, 0x8b0aa8, 0x9, 0x0, 0x0)
        E:/bin/golib/src/github.com/qor/admin/context.go:180 +0x81d
github.com/qor/admin.(_controller).Dashboard(0x115cce68, 0x115da200)
        E:/bin/golib/src/github.com/qor/admin/controller.go:23 +0x3c
github.com/qor/admin.(_controller).Dashboard-fm(0x115da200)
        E:/bin/golib/src/github.com/qor/admin/route.go:109 +0x28
github.com/qor/admin.(_Admin).compile.func2(0x115da200, 0x11559980)
        E:/bin/golib/src/github.com/qor/admin/route.go:337 +0x818
github.com/qor/admin.Middleware.Next(0x8b09f8, 0xa, 0x115cc868, 0x11559980, 0x115da200)
        E:/bin/golib/src/github.com/qor/admin/route.go:38 +0x31
github.com/qor/admin.(_Admin).compile.func1(0x115da200, 0x11559970)
        E:/bin/golib/src/github.com/qor/admin/route.go:307 +0x91
github.com/qor/admin.(_Admin).ServeHTTP(0x116caea0, 0x3208fb08, 0x114fe280, 0x115b68c0)
        E:/bin/golib/src/github.com/qor/admin/route.go:386 +0x64c
net/http.(_ServeMux).ServeHTTP(0x11856060, 0x3208fb08, 0x114fe280, 0x115b68c0)
        E:/bin/go1.6/src/net/http/server.go:1910 +0x133
net/http.serverHandler.ServeHTTP(0x116c8e60, 0x3208fb08, 0x114fe280, 0x115b68c0)
        E:/bin/go1.6/src/net/http/server.go:2081 +0x156
net/http.(_conn).serve(0x115da100)
        E:/bin/go1.6/src/net/http/server.go:1472 +0xed8
created by net/http.(_Server).Serve
        E:/bin/go1.6/src/net/http/server.go:2137 +0x394

how to fix it? Thanks.

**Comment by jaytaylor** [comment]
I've run into this too.  It seems to be due to the assets not being available on disk.  I wish I knew how to get it to bundled the assets at compile time.

**Comment by jaytaylor** [comment]
@listeng I actually solved this, it's an issue of the binary assets not being compiled in and bundled with the built binary.

My solution:

    mkdir bindatafs
    cp -r $GOPATH/src/github.com/qor/admin/views bindatafs/templates
    cp $GOPATH/src/github.com/qor/qor-example/config/admin/bindatafs/bindatafs.go bindatafs/

bindatafs/gen.go:

```(go)
package bindatafs

//go:generate bash -c "( command -v go-bindata || go get -u github.com/jteeuwen/go-bindata/... ) && echo 'Generating bindatafs package from templates/...' && cd templates && go-bindata -pkg bindatafs -o ../templates_bindatafs.go ./... && gofmt -w ../templates_bindatafs.go
```

And finally, when you create the Admin object, make sure to set it's asset src:

    myAdmin.SetAssetFS(bindatafs.AssetFS)

Then you're good to go! No more panics!

**Comment by DenisNeustroev** [comment]
@jaytaylor It doesn't work now

**Comment by jaytaylor** [comment]
What do you mean?  I've got it working fine, but only when the instructions
I posted previously are followed.

**Comment by DenisNeustroev** [comment]
@jaytaylor I use fresh qor's libraries, I have done all steps in the instructions for github.com/qor/bindatafs, as well as yours, in all cases after removal of the github.com/qor/admin from GOPATH this error occurs again. So I can't easily pack my server into a docker container .

**Comment by joe-at-startupmedia** [comment]
duplicated in #56
