### ISSUE TITLE
Unable to use JSON fields in gorm structs

### ISSUE THREAD

**Issue by ethanfrey** [qor/admin#39]
I am using gorm with a postgresql db and I want to store a JSONB field on the item.  Ideally this is visible in both the web and api, but if it is only visible in the json api, that is fine as well.

I have gotten other (standard) structs working, but this one just doesn't seem to be happy.  Maybe I am missing a basic point, but I couldn't find it in the documentation or in experimentation....

Here is a simple gorm model:

```
type Translation struct {
	ID int64 `gorm:"column:id;primary_key"`

	CreatedAt time.Time   `gorm:"column:created_at"`
	Author    string      `gorm:"column:author"`
	Title     string      `gorm:"column:title"`
	Object    dbjson.JSON `gorm:"column:object"`
}
```

dbjson.JSON is a custom object that supports the db, wrapping around rawjson...

```
type JSON struct {
	JSON  json.RawMessage
	Valid bool
}

// Scan implements the database/sql.Scanner interface to
// handle JSONB from the db
func (o *JSON) Scan(src interface{}) (err error) {
	var b []byte

	switch t := src.(type) {
	default:
		panic("OMG!")
		return fmt.Errorf("Cannot parse json from type %T", src)
	case string:
		b = []byte(t)
	case []byte:
		b = t
	}

	if len(b) > 0 {
		err = o.JSON.UnmarshalJSON(b)
		o.Valid = true
		return err
	}
	return nil // null value!
}

// Value implements database/driver.Valuer interface.
//
func (o JSON) Value() (driver.Value, error) {
	if o.Valid {
		return o.JSON.MarshalJSON()
	} else {
		return nil, nil
	}
}
```

Reading/writing this field works in our application code.  Before `Scan` only handled `[]byte`, but I just added some more code to handle `string` as well, and the panic for testing.  I was guessing a fix based on this code from `Meta.Initialize` in `qor/admin` (meta.go:309-312):

```
						if scanner, ok := field.Addr().Interface().(sql.Scanner); ok {
							if scanner.Scan(value) != nil {
								scanner.Scan(utils.ToString(value))
							}
```

I am happy to change the type I use for json serialization, and how it is displayed.  The only essential piece is that a JSONB field in our postgresql database is exposed through the admin interface somehow.

Thank you for your help.

**Comment by ethanfrey** [comment]
Okay, I found an answer myself.  Here for anyone else interested.  One caveat - if you use this to work on nested json (eg. one field of your db struct is a map 2or more level deep), you will get a nil panic in `qor/qor/resource/schema.go`.  I am submitting a pull-request with a fix.

The trick is you need to set custom Setter and Getter for the meta object of the field... And the field must be a proper `map[string]interface{}`.  Here my fixed db struct:

```
// add Value() and Scan() like seen here: http://coussej.github.io/2016/02/16/Handling-JSONB-in-Go-Structs/
type ObjData map[string]interface{}

type Translation struct {
	ID int64 `gorm:"column:id;primary_key"`

	CreatedAt time.Time `gorm:"column:created_at"`
	Author    string    `gorm:"column:author"`
	Title     string    `gorm:"column:title"`
	Object    ObjData   `gorm:"column:object"`
}
```

Now, when I bind the model to the admin, I must provide a custom getter and setter for the meta of that Object field:

```
	trans := server.AddResource(&internal.Translation{})
	obj := trans.GetMetaOrNew("Object")
	// custom setter example...
	obj.SetSetter(func(resource interface{}, metaValue *resource.MetaValue, context *qor.Context) {
		o := resource.(*internal.Translation)
		m := metaValueToMap(metaValue, context)
		o.Object = internal.ObjData(m)
	})
	obj.SetValuer(func(value interface{}, context *qor.Context) interface{} {
		o := value.(*internal.Translation)
		return map[string]interface{}(o.Object)
	})
```

 And I provide some helper functions for translating metaValues to a map, as I couldn't find them elsewhere:

```
func metaValueToMap(metaValue *resource.MetaValue, context *qor.Context) map[string]interface{} {
	raw := resolveMetaValue(metaValue, context)
	res, ok := raw.(map[string]interface{})
	if !ok {
		context.AddError(fmt.Errorf("resolveMetaValue didn't return a map..."))
	}
	return res
}

func resolveMetaValue(metaValue *resource.MetaValue, context *qor.Context) interface{} {
	if metaValue.MetaValues == nil {
		// simple case, no more recursion, return value
		return metaValue.Value
	}
	// otherwise, we recurse into a map
	res := map[string]interface{}{}
	for _, v := range metaValue.MetaValues.Values {
		name := v.Name
		sub := resolveMetaValue(v, context)
		if res[name] == nil {
			// first time, just add the interface
			res[name] = sub
		} else if a, ok := res[name].([]interface{}); !ok {
			// second time, we must make it an array
			// (this is how we get metavalues for array... many times same name)
			res[name] = []interface{}{res[name], sub}
		} else {
			// just append to the existing array
			res[name] = append(a, sub)
		}
	}
	return res
}
```

Note: There is a bug when parsing arrays of maps.  The current format makes it impossible to distinguish between a key pointing to a map or to an array of maps with length one.  The exact same format... If you know how to distinguish them, please let me know.

Any corrections and comments on the above code are welcome, I am quite new to qor, and don't understand all the details of the ORM.

**Comment by jinzhu** [comment]
Thank you for your report
