### ISSUE TITLE
Configuration of embedded (has_many) resources

### ISSUE THREAD

**Issue by EugZol** [qor/admin#45]
I have roughly the following setup:

```
users := qor.AddResource(&user.T{}, &admin.Config{Name: (&user.T{}).ModelName()})
// Not showing "PasswordHash"
users.EditAttrs("Name", "Password")
users.Meta(&admin.Meta{Name: "Password", Type: "password", Setter: setPassword})

qor.AddResource(&organization.T{}, &admin.Config{Name: (&organization.T{}).ModelName()})
```

When I'm editing user directly everything is as I want it to. When I'm coming to `organizations` page, clicking "add", and then "add user" — I see the default field set, and callback "setPassword" is not run after creating the user.

Could you please suggest a way to re-use configuration for main user resource in organization sub-resource?

**Comment by raven-chen** [comment]
Hi @EugZol 

This https://doc.getqor.com/metas/collection-edit.html could help you. take a look please.

**Comment by EugZol** [comment]
Thank you very much. Fetching embedded resource with `user := organization.Meta(&admin.Meta{Name: "Users"}).Resource`, and then working with it like usual works like a charm.
