### ISSUE TITLE
Assets and sytems directories listing

### ISSUE THREAD

**Issue by dmitry-udod** [qor/admin#47]
Hello,
First of all, thank you for a great product!
I found some security problem. You can see a list of files for the system directory and  assets directories.
Try ...  link sent to security@getqor.com
You can found here some solutions 
http://golang-nuts.narkive.com/zt8w7MRM/disable-directory-listing-with-http-fileserver#post3

Regards,
Dmytry

**Comment by slava-vishnyakov** [comment]
Frankly, this is a scary issue, this is in one of the exposed files (leaving out the link, of course, because there is a lot of user information exposed, including e-mails, names, password reset tokens):

```json
[{"User":{"Name":"Gabe","Email":"gk[cut_for_security_reasons]@gmail.com","EncryptedPassword":"$2a$12$jS3TFCrZP1[cut_for_security_reasons]","ConfirmationToken":"","ResetPasswordToken":"","Nationality":"US","PreferredLanguage":"en","PreferredUnit":"kilometers","Gender":"male","Birth":"","NewsletterSubscribed":true,"Active":true,"OnBooth":false,"CreatedAt":"2014-...
```

**Comment by jinzhu** [comment]
Hi Dmytry,

Thank you for pointing the issue out.

All of the qor example data is generated from https://github.com/qor/qor-example/tree/master/db/seeds, so there should be no sensitive data in the demo, but we have changed the logic a little bit to make sure it is clearly delineated as demo data (https://github.com/qor/qor-example/commit/a8a89a79ce029ddc5d15cc318f1e0659dab30a50#diff-75451f67f755f4ec9e9319253a22b7e8).

We will follow up by:

Adding https://github.com/qor/filebox to the qor example to explain how to make sure your uploaded data be safe; and
Adding descriptions for the demo site to let users know all data saved/uploaded will be public to everyone.

Thank you.
