### ISSUE TITLE
Is there a way to override nested form attributes?

### ISSUE THREAD

**Issue by jaytaylor** [qor/admin#48]
E.g. if I have a "Store" which can have many "Items", and I want items to have a field like "category", with a predefined slice of strings.

Is it possible to somehow override the category field on the Item form when creating a new Store entry?

**Comment by jinzhu** [comment]
Yes, please refer: https://github.com/qor/qor-example/blob/master/config/admin/admin.go#L166-L189

**Comment by jaytaylor** [comment]
Thank you @jinzhu!
