### ISSUE TITLE
select_many doesn't work with postgresql database

### ISSUE THREAD

**Issue by DenisNeustroev** [qor/admin#50]
I can select many items, but they are not saving.

An error in a terminal:
```golang
Can't set value []string to []models.Service
```

**Comment by thanateros** [comment]
Same problem; my Models:

**Comment by jinzhu** [comment]
Hi All,

It need to be a valid GORM relationship to save it. refer: http://jinzhu.me/gorm/associations.html

**Comment by thanateros** [comment]
Thank you, that got me back on track.
