### ISSUE TITLE
signal: killed

### ISSUE THREAD

**Issue by samsonpaul** [qor/admin#64]
> I am not sure if this is the right place to log this issue, 

When building the server using `go run main.go`, It loads and then `signal: killed` Thats the only error message that it shows and then it halts all the processes.

> This is based on [this demo](https://github.com/qor/qor-example)

I need mention that this has been functioning well till 2 days ago when it just stopped. I am on MacOS v10.12.4 8GB memory RAM, golang v 1.8+ and my database is `MySQL`

**Comment by xert** [comment]
Same issue (and environment) here.

**Comment by xert** [comment]
`go build -ldflags -s` solves the problem, see:

https://github.com/golang/go/issues/19734
https://github.com/golang/go/issues/11887

**Comment by samsonpaul** [comment]
Hello @xert I just figured out what the problem is, that is if you are on a Mac which is caused by using latest xcode with sqlite. I disabled sqlite and I am back up running 

Thanks to @jinzhu
