### ISSUE TITLE
Change endpoint of autogenerated API

### ISSUE THREAD

**Issue by sredXNY** [qor/admin#71]
Hi, I am using Qor-Admin to generate an API that I need. Until now it's working fine, my question is: Can I change the way that the autogenerated endpoint are called?

I mean, for example `http://demo.getqor.com/api/users.json` I don't want the `.json` at the end, instead I want:
http://demo.getqor.com/api/users
Is it possile?

**Comment by jenshult** [comment]
It's possible. Just pass the Accept: application/json header.

**Comment by sredXNY** [comment]
@jenshult thank you!
