### ISSUE TITLE
undefined: sort.SliceStable

### ISSUE THREAD

**Issue by zh-h** [qor/admin#76]
````bash
# github.com/qor/admin
../../github.com/qor/admin/route.go:94: undefined: sort.SliceStable
````

**Comment by jenshult** [comment]
Upgrade to golang 1.8, where sort.SliceStable has been added.

**Comment by zh-h** [comment]
@jenshult Thanks a lot. I Think this module is pretty resemble Django(A python web framework) that I can quickly hand on.
