### ISSUE TITLE
Updates with Models with related entities are being updated upon creation.

### ISSUE THREAD

**Issue by joe-at-startupmedia** [qor/admin#91]
I have a model that has a relation to another model with a gorm foreign key specified. When I create an instance new model from the qor admin crud form and specify a foreign key from the on-to-many selector, SQL debug is showing that it's also updating the related model, even though I am merely associating it's ID with the new model I am creating (not touching anything with the related model). How do I prevent this?

**Comment by ftomza** [comment]
Hi @joe-at-startupmedia!

As an option, look at this http://jinzhu.me/gorm/crud.html#associations
```go
db.Set("gorm:save_associations", false).Save(&user)
```

**Comment by joe-at-startupmedia** [comment]
I believe in qor admin the default Crud functionality for save is handled by the `admin.Resource.SaveHandler` . I have tried the following code but it doesn't seem to work:

```golang
func DisableSaveOnAssociated(resource *admin.Resource) {
  oldSaveHandler := resource.SaveHandler
  resource.SaveHandler = func(value interface{}, context *qor.Context) error {
    context.GetDB().Set("gorm:save_associations", false)
    return oldSaveHandler(value, context)
  }
}
```
Implementation:
```
program = adminResource.AddResource(&models.Program)
DisableSaveOnAssociated(program)
```

In debug mode still seeing the update on the related model when I am adding a program from CRUD. Any ideas?

**Comment by joe-at-startupmedia** [comment]
Revising the function to this seems to work:

```golang
func DisableSaveOnAssociated(resource *admin.Resource) {
  resource.SaveHandler = func(value interface{}, context *qor.Context) error {
    return context.GetDB().Set("gorm:save_associations", false).Save(value).Error
  }
}
```

**Comment by joe-at-startupmedia** [comment]
Marking this as closed, the above implementation was sufficient.
